# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_feedback',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(default=0)),
                ('username', models.CharField(default=0, max_length=20)),
                ('course_id', models.IntegerField(default=0)),
                ('course', models.CharField(default=0, max_length=20)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='student_feedback',
            unique_together=set([('student_id', 'course_id')]),
        ),
    ]
