# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_feedback',
            old_name='id',
            new_name='ID',
        ),
    ]
