# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180727_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_feedback',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_feedback',
            name='course_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_feedback',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
