# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20180727_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_feedback',
            name='course_id',
            field=models.IntegerField(null=True),
        ),
    ]
