# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20180727_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_feedback',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_feedback',
            name='student_id',
            field=models.IntegerField(default=0),
        ),
    ]
