# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20180727_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_feedback',
            name='course_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student_feedback',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
