# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20180727_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
